### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by koolaidmanpavlov** [makupi/pavlov-bot#114]
Hi, many thanks for creating this awesome bot. I am trying to install it on my vultr server, which is running python 3.8.10  - looks like I am getting some 'unsupported errors' - would anyone happen to know how to fix these?

I appreciate any help you may provide. Oh yeah!

root@PavlovKoolaid:~# sudo su -l steam
$ cd ~/pavlov-bot && pipenv install
/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
Installing dependencies from Pipfile.lock (60428a)...
Traceback (most recent call last):▉▉▉▉▉ 0/13 — 00:00:00
  File "/home/steam/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/cli/command.py", line 220, in install
    do_install(
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/core.py", line 1991, in do_install
    do_init(
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/core.py", line 1255, in do_init
    do_install_dependencies(
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/core.py", line 818, in do_install_dependencies
    batch_install(
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/core.py", line 725, in batch_install
    c = pip_install(
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/core.py", line 1427, in pip_install
    r = write_requirement_to_file(
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/core.py", line 1359, in write_requirement_to_file
    line = requirement.line_instance.get_line(
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2553, in line_instance
    self.line_instance = self.get_line_instance()
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2547, in get_line_instance
    return Line(line)
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 171, in __init__
    self.parse()
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1289, in parse
    self.parse_extras()
  File "/home/steam/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 577, in parse_extras
    self.line, extras = pip_shims.shims._strip_extras(self.line)
TypeError: 'NoneType' object is not callable
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/13 — 00:00:00
$ ^C
$ cd ~pavlov-bot && /usr/local/bin/pipenv run python3.8 run.py
-sh: 2: cd: can't cd to ~pavlov-bot
$ cd ~/pavlov-bot && /usr/local/bin/pipenv run python3.8 run.py
/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import bot
  File "/home/steam/pavlov-bot/bot/__init__.py", line 6, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

**Comment by makupi** [comment]
This issue doesn’t seem to be directly related to the bot but rather some issue with installing packages necessary to run it. Will have to look into them, hard to read on mobile.

Could you show me the output of `uname -a` on your server please? @koolaidmanpavlov

**Comment by koolaidmanpavlov** [comment]
Yes sir.. I just appreciate the help.. here is the output

root@PavlovKoolaid:~# uname -a
Linux PavlovKoolaid 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@PavlovKoolaid:~#

**Comment by koolaidmanpavlov** [comment]
root@PavlovKoolaid:~# uname -a
Linux PavlovKoolaid 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@PavlovKoolaid:~#

**Comment by Derpyhsi** [comment]
TEMP FIX: Run as root: pip3 uninstall pipenv
and then pip3 install -I pipenv
~~Pipenv is broken. Fix is coming.~~
https://github.com/pypa/pipenv/issues/4833
If you see this:

/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
 
Wait for pipenv to get updated.

**Comment by Derpyhsi** [comment]
Solved.
Issue: Pipenv bug.
