### ISSUE TITLE
Discord-components removed from pypi

### ISSUE THREAD

**Issue by invicta-nz** [makupi/pavlov-bot#140]
Discord-components (https://github.com/kiki7000/discord.py-components) is no longer being maintained and has been removed from pypi. 

Reported workaround is a manual install from archived github repo:
`pipenv install https://github.com/kiki7000/discord.py-components/archive/refs/tags/2.1.2.tar.gz`

**Comment by invicta-nz** [comment]
@frostyboskitzo I tried your workaround of doing the manual install of discord-components first and still ran into issues getting imports going:

```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import bot
  File "/home/steam/pavlov-bot/bot/__init__.py", line 8, in <module>
    from discord_components import DiscordComponents
  File "/home/steam/.local/share/virtualenvs/pavlov-bot-WoHbs0yw/lib/python3.8/site-packages/discord_components/__init__.py", line 1, in <module>
    from .client import *
  File "/home/steam/.local/share/virtualenvs/pavlov-bot-WoHbs0yw/lib/python3.8/site-packages/discord_components/client.py", line 12, in <module>
    from .component import Component
  File "/home/steam/.local/share/virtualenvs/pavlov-bot-WoHbs0yw/lib/python3.8/site-packages/discord_components/component.py", line 3, in <module>
    from discord import PartialEmoji, Emoji, InvalidArgument
ImportError: cannot import name 'InvalidArgument' from 'discord' (/home/steam/.local/share/virtualenvs/pavlov-bot-WoHbs0yw/lib/python3.8/site-packages/discord/__init__.py)
```
Any chance you tried something else first?

**Comment by invicta-nz** [comment]
@Derpyhsi Any chance you are interested in helping sort some things out? Otherwise it seems likely that the entire buttons system is going to have to be ripped out unless we can get it working with the new libraries.
